name: respec

# author: @MikeRalphson
# issue: https://github.com/OAI/OpenAPI-Specification/issues/1564

#
# This workflow updates the respec 'pretty' rendered versions of the spec 
# on the main branch when the corresponding markdown files change.
#

# run this on push to main
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch: {}

jobs:
  respec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # checkout main branch
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4 # setup Node.js
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci

    - uses: actions/checkout@v4
      with:
        ref: main
        path: docs/deploy

    - name: run main script
      run: scripts/md2html/build.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-respec-version
        base: main
        delete-branch: true
        path: docs/deploy
        labels: Housekeeping
        reviewers: TSC
        title: Update ReSpec versions
        commit-message: Update ReSpec versions
        signoff: true
        body: |
          This pull request is automatically triggered by GitHub action `respec`.

          The versions/v*.md files have changed, so the HTML files are automatically being regenerated.


