name: validate-markdown

# Author: @MikeRalphson
# Issue: https://github.com/OAI/OpenAPI-Specification/issues/2130

# This workflow validates markdown files in the project root.
# It also validates the work-in-progress specification file src/oas.md with slightly different rules.

# run this on pull requests (which includes pushes to their head branch)
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5 # checkout repo content

      - uses: actions/setup-node@v6 # setup Node.js
        with:
          node-version: "20.x"

      - name: Lint work-in-progress spec
        run: npx --yes markdownlint-cli2 --config spec.markdownlint.yaml src/oas.md

      - name: Lint other files
        run: npx --yes markdownlint-cli2 *.md

      - name: Check links in markdown files
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-check
          fail_level: any
          filter_mode: file
